Feature/scim2 users list
alchemyeng/scim2 pull request #1
Opened 2021-06-21 15:31 UTC by gaurav-ahuja-synerzip

- Basic setup for the serverless project
- Core development for the List users API

2021-06-21 16:53 UTC, KarenKelly818 commented
Gaurav, why is there a yarn.lock file here and a package.json?

2021-06-23 05:49 UTC, gaurav-ahuja-synerzip commented
> Gaurav, why is there a yarn.lock file here and a package.json?

@KarenKelly818 

- "Package.json" is used to state the project dependencies and holds metadata
- "Yarn.lock" is used to avoid the dependency compatibility issues, it maintains the installation order and the installed versions of dependencies

2021-06-24 13:24 UTC, KarenKelly818 commented
> > Gaurav, why is there a yarn.lock file here and a package.json?
> 
> @KarenKelly818
> 
> * "Package.json" is used to state the project dependencies and holds metadata
> * "Yarn.lock" is used to avoid the dependency compatibility issues, it maintains the installation order and the installed versions of dependencies

Yes, I'm aware of what they do. Just wondering why you're using yarn instead of npm. We typically use a shrinkwrap file from json for the lock file.

2021-06-24 13:48 UTC, gaurav-ahuja-synerzip commented
> > > Gaurav, why is there a yarn.lock file here and a package.json?
> > 
> > 
> > @KarenKelly818
> > 
> > * "Package.json" is used to state the project dependencies and holds metadata
> > * "Yarn.lock" is used to avoid the dependency compatibility issues, it maintains the installation order and the installed versions of dependencies
> 
> Yes, I'm aware of what they do. Just wondering why you're using yarn instead of npm. We typically use a shrinkwrap file from json for the lock file.

Okay, I wasn't aware of that, I'll update it and use npm with shrinkwrap.

2021-06-28 09:13 UTC, gaurav-ahuja-synerzip commented
@KarenKelly818 Updated the package with npm shrinkwrap.

2021-06-28 15:27 UTC, KarenKelly818 requested changes

2021-06-28 15:27 UTC, KarenKelly818 commented on lib/filterParser.js
> +  worksiteId: 'worksite.id',
Should this be `worksite_id`?

2021-06-28 15:27 UTC, KarenKelly818 commented on lib/searchParamEncoder.js
> +      && param[1] !== 'undefined'
```suggestion
      || param[1] !== 'undefined'
```

2021-06-28 17:04 UTC, petersendidit requested changes

2021-06-28 17:04 UTC, petersendidit commented on models/User.js
> +class User {
Why is this a class? Seems like this could be a function export `parseUserToSCIM`

2021-06-28 17:04 UTC, petersendidit commented on models/User.js
> +  static parseToSCIM (data) {
Would really like to see unit tests for this.

2021-06-28 17:04 UTC, petersendidit commented on models/User.js
> +      )
```suggestion
      data.direct_report_users.map(({ id }) => ({ value: id }))
```

2021-06-28 17:04 UTC, petersendidit commented on mocks/list-users.json
> +        "filter": "active eq true",
Is this really the format of the query string?  Space delimited for the filter?

2021-06-29 05:27 UTC, gaurav-ahuja-synerzip commented on functions/users/list.js
> +    `https://mkode02.alchemy-eng.com/amyskitchen/api/users/?${searchParamEncoder(params)}`,
I'm working on configuring AWS and will create a PR for that within 2 working days.

2021-06-29 05:29 UTC, gaurav-ahuja-synerzip commented on functions/users/list.js
> +        'X-Auth-Token': 'D555CF5BF7706FD8127989BA63DADB7F',
This will also get resolved once I'm done configuring AWS.

2021-06-29 08:29 UTC, gaurav-ahuja-synerzip commented on lib/filterParser.js
> +  worksiteId: 'worksite.id',
According to the manager API docs, it is `worksite.id` but filtering working with both `worksite.id` and `worksite_id`. I'll change it to `worksite_id` then.

2021-06-29 08:59 UTC, gaurav-ahuja-synerzip commented on lib/filterParser.js
> +const filterParser = (params = {}) => {
Yes, the next PR I'm gonna raise is for unit tests.

2021-06-29 09:03 UTC, gaurav-ahuja-synerzip commented on lib/searchParamEncoder.js
> +      && param[1] !== 'undefined'
Actually, it's a negative statement that's why there is `&&` like if it's neither `'undefined'` nor `undefined` then only add to `params`

2021-06-29 09:04 UTC, gaurav-ahuja-synerzip commented on mocks/list-users.json
> +        "filter": "active eq true",
Yes, it's a SCIM standard to define filters.

2021-06-29 10:17 UTC, gaurav-ahuja-synerzip commented on package.json
> +    "aws-sdk": "^2.918.0",
Okay, for now, I can uninstall the `AWS-SDK`, then when I'll be configuring AWS at that moment I'll install v3.

2021-06-29 10:19 UTC, gaurav-ahuja-synerzip commented on models/User.js
> +  static parseToSCIM (data) {
Yes, the next PR I'm gonna raise is for unit tests.

2021-06-29 13:01 UTC, gaurav-ahuja-synerzip commented on models/User.js
> +class User {
I was actually thinking that there will be multiple parsing functions but now I think only individual exported functions will do. It will act as user util functions. I'll fix this as per the comment.

2021-07-01 19:25 UTC, petersendidit approved these changes

2021-07-06 14:17 UTC, KarenKelly818 approved these changes

2021-07-06 14:18 UTC, merged