Authorise the API's using updated DB fields
alchemyeng/scim2 pull request #11
Opened 2021-09-21 13:49 UTC by gaurav-ahuja-synerzip

- Authorise the API's using updated DB fields
- Code refactor

2021-09-21 13:58 UTC, mangeshko approved these changes

2021-09-27 15:56 UTC, KarenKelly818 commented on serverless.yml
> +          cors: true
Why are we enabling CORS?

2021-09-27 16:11 UTC, troy-rudolph commented
@gaurav-ahuja-synerzip @KarenKelly818 @wilsonp68  

Hello.  There are changes here that enable CORS with no restrictions on the origin of the consumer.  This will make possible for browser-based applications to use SCIM-API.  The existing implementation (Python) does not do this.  Thus, it supports non-browser (back-end) intergration with the SCIM-API.  Before we enable brower-based application on the new SCIM implmentation (without any restrictions), I think we should at least discuss it.

Did some sort of CORS issue occur during testing?  In principle, the javacript that is generated by the doc page should have the same origin as the API itself and thus there should be no CORS issue since the browsers default to 'same orgin' when no CORS headers are provided.  

Please explain.  Thank you.

2021-09-27 16:12 UTC, gaurav-ahuja-synerzip commented on serverless.yml
> +          cors: true
The swagger editor was throwing CORS error, that's why enabling the cors.

2021-09-27 16:18 UTC, gaurav-ahuja-synerzip commented
@troy-rudolph @KarenKelly818 
we'll need to deploy the docs to the https://api-dev.myalchemy.com/scim2 if we don't want to enable the CORS.
I enabled the cors to make the swagger doc work on the swagger editor we are using.

2021-09-27 16:45 UTC, gaurav-ahuja-synerzip commented
I have disabled the CORS.

2021-09-28 14:05 UTC, KarenKelly818 approved these changes

2021-09-28 14:12 UTC, troy-rudolph requested changes

2021-09-28 14:12 UTC, troy-rudolph commented on openAPI.yaml
> +  - url: https://api-dev.myalchemy.com/scim2
@gaurav-ahuja-synerzip @KarenKelly818

What is the plan to make the line above contain the value associated with the deployment location?  

Examples" 
local => ?
dev = "url: https://api-dev.myalchemy.com/scim2"
stage = "url: https://api-stage.myalchemy.com/scim2"
prod = "url: https://api.myalchemy.com/scim2"

2021-09-28 15:27 UTC, gaurav-ahuja-synerzip commented on openAPI.yaml
> +  - url: https://api-dev.myalchemy.com/scim2
I'm working on deploying the swagger UI to the same URL for the API's then the URL can be updated from `https://api-dev.myalchemy.com/scim2` to just `/scim2`, then the swagger UI will use `${HOST}/scim2/` URL (HOST is where the swagger UI is deployed), resolves for all the environments.

2021-09-28 18:59 UTC, troy-rudolph approved these changes

2021-09-28 18:59 UTC, merged