SCIM2-21 AWS integration to generate Auth-Sign for manager API
alchemyeng/scim2 pull request #4
Opened 2021-07-13 15:26 UTC by gaurav-ahuja-synerzip

- AWS secret manager to get the secrets
- AWS DynamoDB integration to fetch the manager API URL
- Generate the Authorisation Signature for Manager API using JWT

2021-07-13 15:43 UTC, petersendidit commented on functions/users/list.js
> +        TableName: 'scim-api-client-config',
Where is the config that creates this table?

2021-07-13 19:08 UTC, KarenKelly818 requested changes

2021-07-13 19:08 UTC, KarenKelly818 commented on functions/users/list.js
> +      throw Object.assign(new Error('Invalid / Missing header Client-Key'), {
Since we aren't going to use the client-key in the header, this needs to be cleaned up

2021-07-13 19:08 UTC, KarenKelly818 commented on mocks/functions/users/list-users.json
> +        "Client-Key": "scim01"
lose the client key here; we should be using the bearer token to identify the client

2021-07-14 12:43 UTC, gaurav-ahuja-synerzip commented on functions/users/list.js
> +        TableName: 'scim-api-client-config',
The database entry comes from "/tools/activate_scim.php" this tool. It generates the token for the client and creates the entry for that in this table.

2021-07-14 12:49 UTC, gaurav-ahuja-synerzip commented on functions/users/list.js
> +      throw Object.assign(new Error('Invalid / Missing header Client-Key'), {
Yes, I had a discussion with Troy regarding that. It will need the DynamoDB recreation and PHP tool up-gradation to activate the auth token for the client. For now, I have been using the old DB. Once the new DB and a new PHP tool are ready, I can upgrade the logic.

2021-07-14 17:45 UTC, petersendidit commented on functions/users/list.js
> +        TableName: 'scim-api-client-config',
Ok, but what creates the table?  There isn't any config in the `serverless.yml` for the dynamodb table.

2021-07-15 08:42 UTC, gaurav-ahuja-synerzip commented on functions/users/list.js
> +        TableName: 'scim-api-client-config',
Table already exists on AWS. We don't create it programmatically.

2021-07-16 20:00 UTC, KarenKelly818 submitted a review, later dismissed

2021-07-22 14:42 UTC, troy-rudolph commented on functions/users/list.js
> +        TableName: 'scim-api-client-config',
While it is true that the table already exists, the deployment code must verify the existence of the table, and if it is not present, create it.  Why?  Because the number of possible deployments is not static.  Tomorrow, we may create an account in AWS for demo.sistemlms.com and deploy the SCIM API there so that the sales folk can demo it.  The table must exist after deployment, if the api is  to be useful.

Next week, we may need to construct a test automation env in AWS and deploy the SCIM api there.  Etc.

Additionally, as we have discussed, the current auth scheme requires a non-standard header "Client-Key".  We need, IMO, to redesign the auth scheme such that the bearer token completely identifies the client with special headers that we may not be able to provide when integrating with 3rd party apps.  I know we discussed this in the last grooming meeting.

2021-07-22 14:43 UTC, troy-rudolph requested changes
See my comments at the PR-level.

2021-07-22 14:45 UTC, troy-rudolph commented on functions/users/list.js
> +        TableName: 'scim-api-client-config',
I don't consider this conversation to be resolved.

2021-07-23 14:22 UTC, troy-rudolph approved these changes

2021-07-23 14:25 UTC, troy-rudolph commented
Approved.  The existing auth method can be used so that testing can proceed.  The new auth method and table layout will be added later.

2021-08-02 13:45 UTC, KarenKelly818 approved these changes

2021-08-02 13:45 UTC, merged