User Get by ID and Delete
alchemyeng/scim2 pull request #5
Opened 2021-08-03 13:16 UTC by gaurav-ahuja-synerzip

- User Get by ID API handler
- User Delete API handler

2021-08-03 15:25 UTC, KarenKelly818 requested changes
We also need unit tests around these as well as inline documentation

2021-08-03 15:25 UTC, KarenKelly818 commented on functions/users/delete.js
> +    const clientKey = event?.headers?.['Client-Key'];
Why are you referencing the client-key as part of the header?

2021-08-09 22:26 UTC, KarenKelly818 requested changes
Also, swagger.yaml is deprecated. Please rename to openapi.yaml.

2021-08-09 22:26 UTC, KarenKelly818 commented on functions/users/delete.js
> + * description: "Delete a specific user by user ID"
```suggestion
 * description: "Archive a specific user by user ID"
```

2021-08-17 14:30 UTC, gaurav-ahuja-synerzip commented on functions/users/delete.js
> +    const clientKey = event?.headers?.['Client-Key'];
The token will be coming in the headers, so once I start working on auth I'll just rename the clientKey to token for all the places and it will work.

2021-08-17 16:16 UTC, KarenKelly818 approved these changes

2021-08-17 16:28 UTC, mangeshko approved these changes

2021-08-17 16:28 UTC, merged